name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Run tests
        run: python manage.py test

  git-bisect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run git bisect script
        run: |
          python myscript.py  # Replace with the path to your script

      - name: Show first bad commit
        run: |
          echo "The first bad commit is: $(git bisect log | tail -n 1)"
